[book]
title = "Rust By Practice( Rust 练习实践 )"
description = "Practice Rust by example, exercise and hand-to-hand projects. Written with ❤️ by https://course.rs team"
authors = ["sunface, https://im.dev"]
language = "en"

[output.html.playpen]
editable = true
editor = "ace"

[output.html.fold]
enable = true
level = 1

[output.html]
git-repository-url = "https://github.com/sunface/rust-by-practice"
edit-url-template = "https://github.com/sunface/rust-by-practice/edit/master/zh-CN/{path}"

[rust]
edition = "2021"